name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install required tools
        run: |
          go install github.com/gotify/plugin-api/cmd/gomod-cap@latest
          
      - name: Build the plugin
        run: |
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telegram-plugin
          path: build/*.so
